<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="lidar" params="radius length pos_y">
    <link name="lidar_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
      </collision>
    </link>

    <joint name="lidar_joint" type="fixed">
      <origin xyz="0 ${pos_y} ${length/2}" rpy="0 0 0"/>
      <parent link="chassis_link"/>
      <child link="lidar_link"/>
    </joint>
  </xacro:macro>
</robot>