<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="small_package_grabber_length" value="0.18" />
<xacro:property name="small_package_grabber_width" value="0.33" />
<xacro:property name="small_package_grabber_height" value="0.135" />
<xacro:property name="small_package_grabber_weight" value="2.45" />

  <xacro:macro name="small_package_grabber" params="parent origin">
    <link name="small_package_grabber_link">
      <xacro:inertial_box mass="${small_package_grabber_weight}" x="${small_package_grabber_length}" y="${small_package_grabber_width}" z="${small_package_grabber_height}">
        <origin xyz="0 0 -${height / 2}" rpy="0 0 0"/>
      </xacro:inertial_box>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/small_package_grabber.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${small_package_grabber_length} ${small_package_grabber_width} ${small_package_grabber_height/2}"/>
        </geometry>
      </collision>
    </link>


    <joint name="small_package_grabber_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="small_package_grabber_link"/>
      <origin xyz="${origin}"/>
    </joint>
    <link name="small_package_grabber_roller_1_link">
      <xacro:inertial_cylinder mass="${small_package_grabber_weight}" length="${small_package_grabber_width}" radius="${small_package_grabber_length}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/small_package_grabber_roller.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="yellow"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${small_package_grabber_length}" length="${small_package_grabber_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="small_package_grabber_roller_1_joint" type="continuous">
      <origin xyz="0.035 0.03 -0.04" rpy="0 0 0"/> 
      <parent link="small_package_grabber_link"/>
      <child link="small_package_grabber_roller_1_link"/>
      <axis xyz="1 0 0"/>
    </joint>
    <link name="small_package_grabber_roller_2_link">
      <xacro:inertial_cylinder mass="${small_package_grabber_weight}" length="${small_package_grabber_width}" radius="${small_package_grabber_length}">
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </xacro:inertial_cylinder>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/small_package_grabber_roller.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="yellow"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${small_package_grabber_length}" length="${small_package_grabber_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="small_package_grabber_roller_2_joint" type="continuous">
      <origin xyz="0.035 0.03 0.02" rpy="0 0 0"/>
      <parent link="small_package_grabber_link"/>
      <child link="small_package_grabber_roller_2_link"/>
      <axis xyz="1 0 0"/>
    <mimic joint="small_package_grabber_roller_1_joint" multiplier="1" offset="0"/>

    </joint>
    <link name="small_package_grabber_roller_3_link">
      <xacro:inertial_cylinder mass="${small_package_grabber_weight}" length="${small_package_grabber_width}" radius="${small_package_grabber_length}">
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </xacro:inertial_cylinder>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/small_package_grabber_roller.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="yellow"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${small_package_grabber_length}" length="${small_package_grabber_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="small_package_grabber_roller_3_joint" type="continuous">
      <origin xyz="0.035 -0.02 -0.055" rpy="0 0 0"/>
      <parent link="small_package_grabber_link"/>
      <child link="small_package_grabber_roller_3_link"/>
      <axis xyz="1 0 0"/>
      <mimic joint="small_package_grabber_roller_1_joint" multiplier="-1" offset="0"/>
    </joint>
    <link name="small_package_grabber_roller_4_link">
      <xacro:inertial_cylinder mass="${small_package_grabber_weight}" length="${small_package_grabber_width}" radius="${small_package_grabber_length}">
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      </xacro:inertial_cylinder>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://robot_description/meshes/small_package_grabber_roller.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="yellow"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${small_package_grabber_length}" length="${small_package_grabber_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="small_package_grabber_roller_4_joint" type="continuous">
      <origin xyz="0.035 -0.03 0.02" rpy="0 0 0"/><!-- -0.03 0.1 0.03 -->
      <parent link="small_package_grabber_link"/>
      <child link="small_package_grabber_roller_4_link"/>
      <axis xyz="1 0 0"/>
      <mimic joint="small_package_grabber_roller_1_joint" multiplier="-1" offset="0"/>
    </joint>
  </xacro:macro>
</robot>