controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_controller/MecanumController

joint_state_broadcaster:
  ros__parameters:
    extra_joints: [
      "rear_right_roller_0_joint",
      "rear_right_roller_1_joint",
      "rear_right_roller_2_joint",
      "rear_right_roller_3_joint",
      "rear_right_roller_4_joint",
      "rear_right_roller_5_joint",
      "rear_right_roller_6_joint",
      "rear_right_roller_7_joint",
      "rear_right_roller_8_joint",
      "rear_left_roller_0_joint",
      "rear_left_roller_1_joint",
      "rear_left_roller_2_joint",
      "rear_left_roller_3_joint",
      "rear_left_roller_4_joint",
      "rear_left_roller_5_joint",
      "rear_left_roller_6_joint",
      "rear_left_roller_7_joint",
      "rear_left_roller_8_joint",
      "front_left_roller_0_joint",
      "front_left_roller_1_joint",
      "front_left_roller_2_joint",
      "front_left_roller_3_joint",
      "front_left_roller_4_joint",
      "front_left_roller_5_joint",
      "front_left_roller_6_joint",
      "front_left_roller_7_joint",
      "front_left_roller_8_joint",
      "front_right_roller_0_joint",
      "front_right_roller_1_joint",
      "front_right_roller_2_joint",
      "front_right_roller_3_joint",
      "front_right_roller_4_joint",
      "front_right_roller_5_joint",
      "front_right_roller_6_joint",
      "front_right_roller_7_joint",
      "front_right_roller_8_joint"]

mecanum_controller:
  ros__parameters:
    front_left_joint: "front_left_mecanum_joint"
    front_right_joint: "front_right_mecanum_joint"
    rear_left_joint: "rear_left_mecanum_joint"
    rear_right_joint: "rear_right_mecanum_joint"

    chassis_center_to_axle: 0.104775 #4.125 in to m
    axle_center_to_wheel: 0.10795 #4.25 in
    wheel_radius: 0.0375 #1.5 in

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
