teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
    scale_linear:
      x: 0.7
      y: 0.7

    axis_angular:  # Left thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 1.5

